# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import auth_events_pb2 as auth__events__pb2
GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth_events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthEventEmitterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmitSignup = channel.unary_unary(
                '/auth.AuthEventEmitter/EmitSignup',
                request_serializer=auth__events__pb2.SignupEvent.SerializeToString,
                response_deserializer=auth__events__pb2.EventAck.FromString,
                _registered_method=True)
        self.EmitLogin = channel.unary_unary(
                '/auth.AuthEventEmitter/EmitLogin',
                request_serializer=auth__events__pb2.LoginEvent.SerializeToString,
                response_deserializer=auth__events__pb2.EventAck.FromString,
                _registered_method=True)


class AuthEventEmitterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EmitSignup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthEventEmitterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmitSignup': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitSignup,
                    request_deserializer=auth__events__pb2.SignupEvent.FromString,
                    response_serializer=auth__events__pb2.EventAck.SerializeToString,
            ),
            'EmitLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitLogin,
                    request_deserializer=auth__events__pb2.LoginEvent.FromString,
                    response_serializer=auth__events__pb2.EventAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'auth.AuthEventEmitter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('auth.AuthEventEmitter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthEventEmitter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EmitSignup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthEventEmitter/EmitSignup',
            auth__events__pb2.SignupEvent.SerializeToString,
            auth__events__pb2.EventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/auth.AuthEventEmitter/EmitLogin',
            auth__events__pb2.LoginEvent.SerializeToString,
            auth__events__pb2.EventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
